main: me.wsman217.FlyPlugin.Main
name: Fly
version: 1.0
author: wsman217
description: A plugin that allows you to fly without creative.
commands: 
  fly: 
    description: Allows or takes away flight.
    usage: /fly
    permission: fly.command.use
permissions:
  fly.command.use: 
    descritption: Allows user to use /fly
    default: op