# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green     
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset




Error_Messages:
  Console_Error: "[Fly]:  This is not to be used by the console!"
  
Messages:
  Insufficient_Perms: "You do not have sufficient permissions!"
  Incorrect_Args: "&b[Fly]: &9Incorrect arguement: "
  Use_This: "&b[Fly]: &9Use /fly."
  Fly_On: "&b[Fly]: &aOn."
  Fly_Off: "&b[Fly]: &cOff."
